knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Users\Eya\Downloads\wkhtmltox-0.12.6-1.msvc2015-win64.exe"'
        options:
            enable-javascript: true
            no-stop-slow-scripts: true
            margin-top: 10mm
            margin-right: 10mm
            margin-bottom: 10mm
            margin-left: 10mm
            encoding: UTF-8
