#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\LoginController::login
app_home:
    path: /home
    controller: App\Controller\TypevController::index
app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout
app_front:
    path: /front
    controller: App\Controller\UserController::front
default_route:
    path: /
    controller: App\Controller\UserController::front
