#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\LoginController::login
app_homepage:
    path: /
    controller: App\Controller\TypevController::index
